// Functions not found in current codebase:
// - Async
// - AsyncInvoke
// - AsyncInvokeLater
// - AsyncSettlePromises
// - Attr
// - Buffer
// - CDATASection
// - CapturedTrace
// - CharacterData
// - Context
// - DOMException
// - DOMHandler
// - DOMImplementation
// - DOMParser
// - DocumentFragment
// - DocumentType
// - Document_2
// - ElementAttributes
// - Element_3
// - Entity
// - EntityReference
// - FinallyHandlerCancelReaction
// - HandleWrapper
// - Item
// - LiveNodeList
// - MappingPromiseArray
// - NamedNodeMap
// - Node
// - NodeList
// - Notation
// - OperationalError
// - ParseError
// - PassThroughHandlerContext
// - ProcessingInstruction
// - Promise
// - PromiseArray
// - PromiseInspection
// - PromiseMapSeries
// - PromiseSpawn
// - PropertiesPromiseArray
// - Proxyable
// - Queue
// - ReductionPromiseArray
// - SettledPromiseArray
// - SlowBuffer
// - SomePromiseArray
// - Text_2
// - Timeout
// - XMLReader
// - XMLSerializer
// - __set__
// - _addNamedNode
// - _appendSingleChild
// - _byteLength
// - _copy
// - _extends
// - _findNodeIndex
// - _insertBefore
// - _locator
// - _onAddAttribute
// - _onRemoveAttribute
// - _onUpdateChild
// - _removeChild
// - _removeNamedNode
// - _toString
// - _updateLiveList
// - _updateOwnerDocument
// - _visitNode
// - _xmlEncoder
// - addSerializedAttribute
// - alloc
// - allocUnsafe
// - any
// - appendElement
// - appendElement_2
// - arrayIncludes
// - arrayIndexOf
// - arrayMove
// - asciiSlice
// - asciiToBytes
// - asciiWrite
// - assertPreInsertionValidity1to5
// - assertPreInsertionValidityInDocument
// - assertPreReplacementValidityInDocument
// - assertSize
// - assign
// - base64Slice
// - base64ToBytes
// - base64Write
// - base64clean
// - bidirectionalIndexOf
// - bindingPropagateFrom
// - blitBuffer
// - boundValueFunction
// - buildErrorHandler
// - byteLength
// - byteLength_2
// - caller
// - canAttachTrace
// - cancellationAttachCancellationCallback
// - cancellationClearCancellationData
// - cancellationExecute
// - cancellationOnCancel
// - cancellationPropagateFrom
// - cancellationSetOnCancel
// - catchFilter
// - check
// - checkCancel
// - checkForgottenReturns
// - checkIEEE754
// - checkInt
// - checkOffset
// - checkValid
// - checked
// - classString
// - cleanStack
// - cleanUpNextTick
// - cloneNode
// - codePoint
// - completed
// - consolidated_short_functions
// - copy
// - copyDescriptors
// - copyLocator
// - createBuffer
// - createContext
// - dec
// - decodeCodePointsArray
// - defaultClearTimeout
// - defaultFireEvent
// - defaultSetTimout
// - deferReject
// - deferResolve
// - deprecated
// - doGetThen
// - doThenable
// - domainBind
// - drainQueue
// - element_2
// - elements_2
// - encodeChunk
// - ensureMethod
// - env
// - errorAdapter
// - extractTextFromElements
// - fail
// - failureClear
// - filledRange
// - finallyHandler
// - find
// - fireRejectionEvent
// - fixSelfClosed
// - flatMap_2
// - formatAndLogError
// - formatNonError
// - freeze
// - from
// - fromArrayBuffer
// - fromArrayLike
// - fromByteArray
// - fromCodePointPolyfill
// - fromObject
// - fromString
// - generatePromiseLifecycleEventObject
// - getDataPropertyOrDefault
// - getLens
// - getNativePromise
// - getThen
// - gotAccum
// - gotValue
// - hasInsertableNodeType
// - hasPromisified
// - hasValidParentNodeType
// - hex
// - hexSlice
// - hexWrite
// - identity_2
// - identity_3
// - importNode
// - indexedGetter
// - introduction
// - isAnyBluebirdPromise
// - isClass
// - isDocTypeNode
// - isElementInsertionPossible
// - isElementNode
// - isElementReplacementPossible
// - isError
// - isIdentifier
// - isObject
// - isPrimitive
// - isPromisified
// - isTextNode
// - isUntypedError
// - isnan
// - kMaxLength
// - latin1Slice
// - latin1Write
// - longStackTracesAttachExtraTrace
// - longStackTracesCaptureStackTrace
// - longStackTracesIsSupported
// - makeNodePromisifiedClosure
// - markAsOriginatingFromRejection
// - maybeWrapAsError
// - namedGetter
// - needNamespaceDefine
// - nodeSerializeToString
// - nodebackForPromise
// - noop
// - normalizeLineEndings
// - notEmptyString
// - notEnumerableProp
// - objectWriteUInt16
// - objectWriteUInt32
// - orderedSetReducer
// - originatesFromRejection
// - paragraph_2
// - parse
// - parseDCC
// - parseElementStartPart
// - parseHtmlSpecialContent
// - parseInstruction
// - parseLineInfo
// - parseStackAndMessage
// - peekContext
// - position
// - promiseAllThis
// - promiseFromYieldHandler
// - promisifiableMethods
// - promisifyAll
// - propsFilter
// - race
// - readStyleMap_2
// - read_2
// - reconstructStack
// - reduce
// - removeCommonRoots
// - removeDuplicateOrEmptyJumps
// - returner
// - runClearTimeout
// - runTimeout
// - run_2
// - safeToString
// - serializeToString
// - setBounds
// - slowToString
// - snip
// - some
// - split
// - splitOnASCIIWhitespace
// - spreadAdapter
// - stackFramesAsArray
// - stringtrim
// - subError
// - succeed
// - successAdapter
// - successClear
// - swap
// - thrower
// - thrower_2
// - toByteArray
// - toFastProperties
// - toHex
// - toOrderedSet
// - toResolutionValue
// - tripletToBase64
// - tryCatch
// - tryCatcher
// - tryConvertToPromise
// - typedArraySupport
// - ucs2Write
// - utf16leSlice
// - utf16leToBytes
// - utf8Slice
// - utf8ToBytes
// - utf8Write
// - withAppended
// - wrapAsOperationalError
// - writeDouble
// - writeFloat
// - writer_2
