/**
 * @license GPL-3.0-only
 * html-to-docx-with-style — Ritápolis, Minas Gerais, Brasil
 * Copyright (c) 2026 Arthur Rodrigues
 * https://github.com/arthrod/html-to-docx-with-style
 * @preserve
 */
import { $ as footerFileName, A as applicationName, B as commentsIdsType, C as generateHexId, D as wrapRunWithSuggestion, E as splitDocxTrackingTokens, F as commentsExtensibleContentType, G as defaultFontSize, H as defaultDirection, I as commentsExtensibleRelationshipType, J as defaultLang, K as defaultHTMLString, L as commentsExtensibleType, M as commentsExtendedContentType, N as commentsExtendedRelationshipType, O as namespaces, P as commentsExtendedType, Q as documentFileName, R as commentsIdsContentType, S as findDocxTrackingTokens, T as resetAllocatedIds, U as defaultDocumentOptions, V as commentsType, W as defaultFont, X as defaultTableBorderAttributeOptions, Y as defaultOrientation, Z as defaultTableBorderOptions, _ as buildDeletedTextElement, _t as themeType, a as DOCX_DELETION_END_TOKEN_PREFIX, at as internalRelationship, b as buildTextElement, c as DOCX_INSERTION_END_TOKEN_PREFIX, ct as landscapeWidth, d as allocatedIds, dt as peopleRelationshipType, et as footerType, f as buildCommentEndToken, ft as peopleType, g as buildCommentStartToken, gt as themeFolder, h as buildCommentReferenceRun, ht as themeFileName, i as DOCX_COMMENT_TOKEN_SUFFIX, it as imageType, j as colorlessColors, k as SVG_UNIT_TO_PIXEL_CONVERSIONS, l as DOCX_INSERTION_START_TOKEN_PREFIX, lt as paragraphBordersObject, m as buildCommentRangeStart, mt as relsFolderName, n as DOCX_COMMENT_END_TOKEN_PREFIX, nt as headerType, o as DOCX_DELETION_START_TOKEN_PREFIX, ot as landscapeHeight, p as buildCommentRangeEnd, pt as portraitMargins, q as defaultHeadingOptions, r as DOCX_COMMENT_START_TOKEN_PREFIX, rt as hyperlinkType, s as DOCX_DELETION_TOKEN_SUFFIX, st as landscapeMargins, t as generateContainer, tt as headerFileName, u as DOCX_INSERTION_TOKEN_SUFFIX, ut as peopleContentType, v as buildSuggestionEndToken, vt as verticalAlignValues, w as hasTrackingTokens, x as ensureTrackingState, y as buildSuggestionStartToken, yt as wordFolder, z as commentsIdsRelationshipType } from "./node-DUXXn-5d.js";
export { DOCX_COMMENT_END_TOKEN_PREFIX, DOCX_COMMENT_START_TOKEN_PREFIX, DOCX_COMMENT_TOKEN_SUFFIX, DOCX_DELETION_END_TOKEN_PREFIX, DOCX_DELETION_START_TOKEN_PREFIX, DOCX_DELETION_TOKEN_SUFFIX, DOCX_INSERTION_END_TOKEN_PREFIX, DOCX_INSERTION_START_TOKEN_PREFIX, DOCX_INSERTION_TOKEN_SUFFIX, generateContainer as HTMLtoDOCX, generateContainer as default, SVG_UNIT_TO_PIXEL_CONVERSIONS, allocatedIds, applicationName, buildCommentEndToken, buildCommentRangeEnd, buildCommentRangeStart, buildCommentReferenceRun, buildCommentStartToken, buildDeletedTextElement, buildSuggestionEndToken, buildSuggestionStartToken, buildTextElement, colorlessColors, commentsExtendedContentType, commentsExtendedRelationshipType, commentsExtendedType, commentsExtensibleContentType, commentsExtensibleRelationshipType, commentsExtensibleType, commentsIdsContentType, commentsIdsRelationshipType, commentsIdsType, commentsType, defaultDirection, defaultDocumentOptions, defaultFont, defaultFontSize, defaultHTMLString, defaultHeadingOptions, defaultLang, defaultOrientation, defaultTableBorderAttributeOptions, defaultTableBorderOptions, documentFileName, ensureTrackingState, findDocxTrackingTokens, footerFileName, footerType, generateHexId, hasTrackingTokens, headerFileName, headerType, hyperlinkType, imageType, internalRelationship, landscapeHeight, landscapeMargins, landscapeWidth, namespaces, paragraphBordersObject, peopleContentType, peopleRelationshipType, peopleType, portraitMargins, relsFolderName, resetAllocatedIds, splitDocxTrackingTokens, themeFileName, themeFolder, themeType, verticalAlignValues, wordFolder, wrapRunWithSuggestion };
